name: Build and push to pypi

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.11
          poetry-version: 1.3.1
          token: ${{ secrets.PYPI_TOKEN }}
          build: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          body_path: CHANGELOG.md